### PR TITLE
ps2klsi build fix / Build system cleanup

### PR DESCRIPTION
**Pull request by uyjulian**
ps2klsi build has been fixed. However, it has not been tested because I do not have the hardware to test it.

Build system was cleaned up, and `install` rule now depends on `all` rule.

### CODE REVIEW

**Comment by rickgaiser** [comment]
Who does use it? It looks like the code has been non-working for quite some time.
The same for the linux driver, who uses it?
The same for the smap driver, it's used by ps2link, but why doesn't ps2link use the smap driver from ps2sdk instead?

What I'm saying is, can't we remove this git repository and keep the smap driver in ps2sdk?

**Comment by uyjulian** [comment]
uLaunchELF uses the smap driver from this repository.

I'm not sure of the changes of the smap driver between this repository and the one in ps2sdk.

**Comment by sp193** [comment]
A long time ago, in a world not too far away...
The de-facto homebrew SMAP driver was in ps2eth. It was based on the PS2Linux code and had no support for DMA. It was also made to be directly coupled with LWIP, both of which ran on the IOP. For some reason, it also seemed to have problems with auto-negotiation.

As hard as I tried, I could not figure out how to get DMA support working reliably (hardware kept freezing up). In 2013, I copied the Sony SMAP driver for the proper DMA support and wrote my own network manager (NETMAN), to allow LWIP to be run from either the EE or IOP. It also involved upgrading DEV9 to have the latest design, as it was clear that Sony was working around some hardware restrictions.
But the use of NETMAN is not backward-compatible, in terms of the protocol stack and the SMAP driver. And since I was alone making decisions in a long time - I decided at that time to keep the old code in ps2eth, for backward-compatibility. Some niche cases would perhaps still need the direct coupling with the LWIP stack anyway (e.g. something like OPL in-game, although OPL doesn't use this module), so it's also useful as a reference. You'll find different versions of the IOP LWIP driver in the PS2SDK: ps2ip (classic module for direct coupling), ps2ip-nm (for use with NETMAN)

As for the driver for the Kawasaki chipset, I don't know the story of that one. I presume someone had that device and wrote a module to get it to work.

**Comment by rickgaiser** [comment]
Some time ago I made this:

LwIP_stack_v2

I still intend to add it to the documentation somewhere. Becouse without an overview like this, the network stack will be very difficult to understand. So basically option 1 and 2 using NETMAN, are in ps2sdk. And option 3, is in this repository.

Should we migrate all software to the (option 2) ps2sdk versions? Like uLE/ps2link?
Or move the "option 3" driver to ps2sdk?

> Some niche cases would perhaps still need the direct coupling with the LWIP stack anyway (e.g. something like OPL in-game, although OPL doesn't use this module), so it's also useful as a reference.

Another copy of the same driver :(. Shouldn't OPL in-game use the drivers from ps2sdk also?

**Comment by sp193** [comment]
OPL, if it still uses SMSTCPIP, would have to use a different SMAP driver. By having direct coupling to the LWIP library, SMAP must be built against a compatible LWIP library. SMSTCPIP might have been based on an old version of LWIP, which we could possibly treat as compatible with v1.1.1 - which was one of the original LWIP versions in our PS2SDK. Even so, I remember there were some differences in its interfaces, perhaps because it was originally an even older version of LWIP.

And so I do not believe you can get it to use any of these other SMAP drivers.

**Comment by sp193** [comment]
As for migration - I would recommend it for new software, unless you (or somebody) would not mind investing in the effort to update the old software. NETMAN also offers API to configure the interface settings in realtime, like link negotiation, speed and duplex.
Ideally, software that use the network should allow the user to also configure those settings. It's a bit unfortunate, but the PS2's network adaptor doesn't seem to have a 100% compatibility rate.

EDIT: to clarify, it is also possible with the old design too, although it is not possible to change the settings dynamically. Setting those parameters can be done with the newer SMAP driver from PS2ETH, through module parameters. So they are set once, with the module's startup. I forgot if it's possible with the PS2Linux SMAP driver.

**Comment by uyjulian** [comment]
Migration can be done in the future. For now, this PR cleans up the build system (using sample makefiles whenever possible) and fixes the build of the driver for the Kawasaki chipset.

**Pull request merged**
